spring:
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        #最大连接阻塞时间
        max-wait: 10000ms
        #最大空闲连接，默认8
        max-idle: 200
        #最小空闲连接，默认0
        min-idle: 5
    password: test123

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 12345678
    hikari:
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认10分钟，给了半小时
      idle-timeout: 180000
      maximum-pool-size: 10
      #连接池返回的连接自动提交
      auto-commit: true
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
mybatis-plus:
  mapper-locations: classpath*:/mapper/*Mapper.xml
  type-aliases-package: xyz.jyke.seckill.pojo

logging:
  level:
    xyz.jyke.seckill.mapper: debug

